# Generated by Django 5.0.1 on 2024-01-31 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.CharField(verbose_name='Available time')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Photo')),
                ('first_name', models.CharField(max_length=80, verbose_name='First name')),
                ('last_name', models.CharField(max_length=80, verbose_name='Last name')),
                ('about', models.TextField(blank=True, max_length=600, verbose_name='Information about doctor')),
                ('experience', models.TextField(blank=True, verbose_name='Experience')),
                ('price', models.IntegerField(blank=True, default=None, verbose_name='Visit price')),
            ],
        ),
        migrations.CreateModel(
            name='SpecializationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_title', models.CharField(verbose_name='Specialization title')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('appointment_datetime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appointmenttime')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='main.specializationcategory'),
        ),
    ]
