# Generated by Django 5.0.1 on 2024-02-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, verbose_name='User callback name')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='User callback email')),
                ('phone', models.CharField(default=None, max_length=20)),
                ('date', models.DateField(default=None)),
            ],
        ),
    ]
