# Generated by Django 5.0.1 on 2024-02-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_callback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='price',
        ),
    ]
